/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Karthik
 */
public class ManageRestuarants extends javax.swing.JPanel {

    /**
     * Creates new form ManageRestuarants
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public ManageRestuarants(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        ecosystem = dB4OUtil.retrieveSystem();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        restable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RestuarantNamejfld = new javax.swing.JTextField();
        resUnamefld = new javax.swing.JTextField();
        respwdfld = new javax.swing.JTextField();
        resaddrfld = new javax.swing.JTextField();
        respnofld = new javax.swing.JTextField();
        createResbtn = new javax.swing.JButton();
        Modifyresbtn = new javax.swing.JButton();
        delresbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        restable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Address", "Phone Number", "UserName", "Password"
            }
        ));
        jScrollPane1.setViewportView(restable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RESTUARANT MANAGEMENT");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Restuarant Name");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Name");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone Number");

        createResbtn.setText("Create");
        createResbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createResbtnActionPerformed(evt);
            }
        });

        Modifyresbtn.setText("Modify");
        Modifyresbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyresbtnActionPerformed(evt);
            }
        });

        delresbtn.setText("Delete");
        delresbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delresbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(RestuarantNamejfld)
                        .addComponent(resUnamefld)
                        .addComponent(respwdfld)
                        .addComponent(resaddrfld)
                        .addComponent(respnofld, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createResbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Modifyresbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delresbtn)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(RestuarantNamejfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(resUnamefld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(respwdfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(resaddrfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(respnofld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createResbtn)
                    .addComponent(Modifyresbtn)
                    .addComponent(delresbtn))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createResbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createResbtnActionPerformed
        // TODO add your handling code here:
        if(resUnamefld.getText().isEmpty() || respwdfld.getText().isEmpty() || resaddrfld.getText().isEmpty() || respnofld.getText().isEmpty() || RestuarantNamejfld.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "please enter all mandatory fields");
            return;
        }
        if(ecosystem.getUserAccountDirectory().checkIfUsernameIsUnique(resUnamefld.getText())) {
            Restaurant R = new Restaurant(resUnamefld.getText(),respwdfld.getText(),RestuarantNamejfld.getText(),resaddrfld.getText(),respnofld.getText());
            ecosystem.getUserAccountDirectory().addUserAcount(R);
            ecosystem.getRestaurantDirectory().addRestaurant(R);
            populateTable();
            resUnamefld.setText("");
            respwdfld.setText("");
            RestuarantNamejfld.setText("");
            resaddrfld.setText("");
            respnofld.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Username " + resUnamefld.getText() + " already exists !!!, Please try a new one");
        }
    }//GEN-LAST:event_createResbtnActionPerformed

    private void ModifyresbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyresbtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = restable.getSelectedRow();
        if (selectedRow >= 0) {
            Restaurant r = (Restaurant) restable.getValueAt(selectedRow, 0);
            r.setUsername(resUnamefld.getText());
            r.setName(RestuarantNamejfld.getText());
            r.setPassword(respwdfld.getText());
            r.setAddress(resaddrfld.getText());
            r.setPhone(respnofld.getText());
            populateTable();
            resUnamefld.setText("");
            respwdfld.setText("");
            RestuarantNamejfld.setText("");
            resaddrfld.setText("");
            respnofld.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_ModifyresbtnActionPerformed

    private void delresbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delresbtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = restable.getSelectedRow();

        if (selectedRow >= 0) {
            Restaurant restaurant = (Restaurant) restable.getValueAt(selectedRow, 0);
            RestaurantDirectory restaurantDirectory = ecosystem.getRestaurantDirectory();
            restaurantDirectory.RemoveRestaurant(restaurant);
            JOptionPane.showMessageDialog(null, "Restaurant admin "  + resUnamefld.getText() + " deleted");
            populateTable();
            resUnamefld.setText("");
            respwdfld.setText("");
            RestuarantNamejfld.setText("");
            resaddrfld.setText("");
            respnofld.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }
    }//GEN-LAST:event_delresbtnActionPerformed

private void populateTable() {
    RestaurantDirectory rd = ecosystem.getRestaurantDirectory();
    DefaultTableModel model = (DefaultTableModel) restable.getModel();

        model.setRowCount(0);
        for (Restaurant R : rd.getRestaurantList()) {
                    Object[] row = new Object[5];
                    row[0] = R;
                    row[1] = R.getAddress();
                    row[2] = R.getPhone();
                    row[3] = R.getUsername();
                    row[4] = R.getPassword();

                    model.addRow(row);
                
            }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Modifyresbtn;
    private javax.swing.JTextField RestuarantNamejfld;
    private javax.swing.JButton createResbtn;
    private javax.swing.JButton delresbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField resUnamefld;
    private javax.swing.JTextField resaddrfld;
    private javax.swing.JTextField respnofld;
    private javax.swing.JTextField respwdfld;
    private javax.swing.JTable restable;
    // End of variables declaration//GEN-END:variables
}
