/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.DB4OUtil.DB4OUtil;
import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Karthik
 */
public class ManageDeliveryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDeliveryJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public ManageDeliveryJPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = this.userProcessContainer;
        this.ecosystem = ecosystem;
        ecosystem = dB4OUtil.retrieveSystem();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DeliveryTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DeliveryNameJfld = new javax.swing.JTextField();
        DeliveryPnofld = new javax.swing.JTextField();
        deliveryunamefld = new javax.swing.JTextField();
        deliverypassfld = new javax.swing.JTextField();
        deliverycreate = new javax.swing.JButton();
        deliverymodify = new javax.swing.JButton();
        deliverydelete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 153));

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        DeliveryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Phone Number", "User Name", "Password"
            }
        ));
        jScrollPane1.setViewportView(DeliveryTable);

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Phone Number");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Name");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");

        DeliveryNameJfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryNameJfldActionPerformed(evt);
            }
        });

        deliverypassfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverypassfldActionPerformed(evt);
            }
        });

        deliverycreate.setText("Create");
        deliverycreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverycreateActionPerformed(evt);
            }
        });

        deliverymodify.setText("Modify");
        deliverymodify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverymodifyActionPerformed(evt);
            }
        });

        deliverydelete.setText("Delete");
        deliverydelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverydeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(deliverycreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deliverymodify)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deliverydelete)
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addComponent(DeliveryNameJfld)
                    .addComponent(DeliveryPnofld)
                    .addComponent(deliveryunamefld)
                    .addComponent(deliverypassfld))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(DeliveryNameJfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(DeliveryPnofld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(deliveryunamefld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(deliverypassfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliverycreate)
                    .addComponent(deliverymodify)
                    .addComponent(deliverydelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MANAGE DELIEVRY PERSONS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DeliveryNameJfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryNameJfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeliveryNameJfldActionPerformed

    private void deliverypassfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverypassfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deliverypassfldActionPerformed

    private void deliverycreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverycreateActionPerformed
        // TODO add your handling code here:
        if(DeliveryNameJfld.getText().isEmpty() || DeliveryPnofld.getText().isEmpty() || deliveryunamefld.getText().isEmpty()|| deliverypassfld.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "please enter all mandatory fields");
            return;
        }
        if(ecosystem.getUserAccountDirectory().checkIfUsernameIsUnique(deliveryunamefld.getText())) {
            DeliveryMan dm = new DeliveryMan(deliveryunamefld.getText(), deliverypassfld.getText(), DeliveryNameJfld.getText(), DeliveryPnofld.getText());
            ecosystem.getUserAccountDirectory().addUserAcount(dm);
            ecosystem.getDeliveryManDirectory().addtoDeliveryManDirectory(dm);
            populateTable();
            DeliveryNameJfld.setText("");
            DeliveryPnofld.setText("");
            deliverypassfld.setText("");
            deliveryunamefld.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Username " + deliveryunamefld.getText() + " already exists !!!, Please try a new one");
        }
    }//GEN-LAST:event_deliverycreateActionPerformed

    private void deliverymodifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverymodifyActionPerformed
        // TODO add your handling code here:
         int selectedRow = DeliveryTable.getSelectedRow();
        if (selectedRow >= 0) {
            DeliveryMan dm = (DeliveryMan) DeliveryTable.getValueAt(selectedRow, 0);
            dm.setUsername(deliveryunamefld.getText());
            dm.setName(DeliveryNameJfld.getText());
            dm.setPassword(deliverypassfld.getText());
            dm.setPhone(DeliveryPnofld.getText());
            populateTable();
            deliveryunamefld.setText("");
            deliverypassfld.setText("");
            DeliveryNameJfld.setText("");
            DeliveryPnofld.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_deliverymodifyActionPerformed

    private void deliverydeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverydeleteActionPerformed
        // TODO add your handling code here:
         int selectedRow = DeliveryTable.getSelectedRow();

        if (selectedRow >= 0) {
            DeliveryMan dm = (DeliveryMan) DeliveryTable.getValueAt(selectedRow, 0);
            DeliveryManDirectory dmd = ecosystem.getDeliveryManDirectory();
            dmd.removefromDeliveryManDirectory(dm);
            JOptionPane.showMessageDialog(null, "Delivery person   "  + deliveryunamefld.getText() + " deleted");
            populateTable();
             deliveryunamefld.setText("");
            deliverypassfld.setText("");
            DeliveryNameJfld.setText("");
            DeliveryPnofld.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }
    }//GEN-LAST:event_deliverydeleteActionPerformed

private void populateTable() {
    DeliveryManDirectory dc = ecosystem.getDeliveryManDirectory();
    DefaultTableModel model = (DefaultTableModel) DeliveryTable.getModel();

        model.setRowCount(0);
        for (DeliveryMan deliveryman : dc.getDeliveryManDirectory()) {
                    Object[] row = new Object[5];
                    row[0] = deliveryman;
                    row[1] = deliveryman.getPhone();
                    row[2] = deliveryman.getUsername();
                    row[3] = deliveryman.getPassword();
                    model.addRow(row);
                
            }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DeliveryNameJfld;
    private javax.swing.JTextField DeliveryPnofld;
    private javax.swing.JTable DeliveryTable;
    private javax.swing.JButton deliverycreate;
    private javax.swing.JButton deliverydelete;
    private javax.swing.JButton deliverymodify;
    private javax.swing.JTextField deliverypassfld;
    private javax.swing.JTextField deliveryunamefld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
