/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.Customer.Customer;
import Business.DB4OUtil.DB4OUtil;
import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author nisar
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginJPanel
     */
    private JPanel Container;
    private EcoSystem system;
    private UserAccount userAccount;
    private DB4OUtil dB4Util = DB4OUtil.getInstance();
    public LoginJPanel(JPanel Container, EcoSystem system) {
        initComponents();
        this.Container=Container;
        this.system=system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jusernamelbl = new javax.swing.JLabel();
        JPasswordlbl = new javax.swing.JLabel();
        JUserfld = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        Jloginbtn = new javax.swing.JButton();

        Jusernamelbl.setText("User Name");

        JPasswordlbl.setText("Password");

        JUserfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUserfldActionPerformed(evt);
            }
        });

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        Jloginbtn.setText("LOGIN");
        Jloginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JloginbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jusernamelbl)
                        .addGap(18, 18, 18)
                        .addComponent(JUserfld))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JPasswordlbl)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jloginbtn)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JPasswordlbl, Jusernamelbl});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jusernamelbl)
                    .addComponent(JUserfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JPasswordlbl)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(Jloginbtn)
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JUserfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUserfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JUserfldActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed
private void changeviewJPanel(UserAccount usa) {
    if(usa!= null) {
        if(usa instanceof Customer) {
            
        } else if(usa instanceof Restaurant) {
        
        } else if(usa instanceof DeliveryMan) {
            
        } else {
            Container.add("workArea", usa.getRole().createWorkArea(Container, userAccount, system));
        }
        CardLayout layout = (CardLayout) Container.getLayout();
        layout.next(Container);
    }
}
    private void JloginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JloginbtnActionPerformed
        // TODO add your handling code here:
        String userName = JUserfld.getText();
        char[] passwordCharArray = jPasswordField1.getPassword();
        String password = String.valueOf(passwordCharArray);
        userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);
        if(userAccount == null){
            JOptionPane.showMessageDialog(this, "Invalid credentials");
            return;
        }else{
            JUserfld.setText("");
            jPasswordField1.setText("");
            changeviewJPanel(userAccount);
        }
        
    }//GEN-LAST:event_JloginbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JPasswordlbl;
    private javax.swing.JTextField JUserfld;
    private javax.swing.JButton Jloginbtn;
    private javax.swing.JLabel Jusernamelbl;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
