/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.AddressInfo;

/**
 *
 * @author nisar
 */
public class AddresInfoViewJpanel extends javax.swing.JPanel {

    AddressInfo address;
   
    public AddresInfoViewJpanel(AddressInfo address) {
        initComponents();
        this.address=address;
        displayProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddressTitleLbl = new javax.swing.JLabel();
        StreetLbl = new javax.swing.JLabel();
        CityLbl = new javax.swing.JLabel();
        StateLbl = new javax.swing.JLabel();
        ZipcodeLbl = new javax.swing.JLabel();
        StreetTxtFld = new javax.swing.JTextField();
        CityTxtFld = new javax.swing.JTextField();
        ZipcodeTxtFld = new javax.swing.JTextField();
        StateTxtFld = new javax.swing.JTextField();

        AddressTitleLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddressTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddressTitleLbl.setText("Address Info");

        StreetLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StreetLbl.setText("Street");

        CityLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CityLbl.setText("City");

        StateLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StateLbl.setText("State");

        ZipcodeLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ZipcodeLbl.setText("Zipcode");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ZipcodeLbl)
                        .addGap(57, 57, 57)
                        .addComponent(ZipcodeTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(StateTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(CityTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(StreetLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(StreetTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)))
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddressTitleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CityLbl, StateLbl, StreetLbl, ZipcodeLbl});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddressTitleLbl)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StreetLbl)
                    .addComponent(StreetTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityLbl)
                    .addComponent(CityTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StateLbl)
                    .addComponent(StateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZipcodeLbl)
                    .addComponent(ZipcodeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {CityLbl, StateLbl, StreetLbl, ZipcodeLbl});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressTitleLbl;
    private javax.swing.JLabel CityLbl;
    private javax.swing.JTextField CityTxtFld;
    private javax.swing.JLabel StateLbl;
    private javax.swing.JTextField StateTxtFld;
    private javax.swing.JLabel StreetLbl;
    private javax.swing.JTextField StreetTxtFld;
    private javax.swing.JLabel ZipcodeLbl;
    private javax.swing.JTextField ZipcodeTxtFld;
    // End of variables declaration//GEN-END:variables

private void displayProduct() {
        StreetTxtFld.setText(address.getStreatAdrss());
        CityTxtFld.setText(address.getCity());
        StateTxtFld.setText(address.getState());
        ZipcodeTxtFld.setText(address.getZipcode());
}
}
