/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.AddressInfo;
import model.Person;

/**
 *
 * @author nisar
 */
public class AddresInfoCreateJpanel extends javax.swing.JPanel {

    AddressInfo address;
    Person person;
    public AddresInfoCreateJpanel(AddressInfo address,Person person) {
        initComponents();
        this.address=address;
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddressTitleLbl = new javax.swing.JLabel();
        StreetLbl = new javax.swing.JLabel();
        CityLbl = new javax.swing.JLabel();
        StateLbl = new javax.swing.JLabel();
        ZipcodeLbl = new javax.swing.JLabel();
        StreetTxtFld = new javax.swing.JTextField();
        CityTxtFld = new javax.swing.JTextField();
        ZipcodeTxtFld = new javax.swing.JTextField();
        StateTxtFld = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();

        AddressTitleLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddressTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddressTitleLbl.setText("Address Info");

        StreetLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StreetLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        StreetLbl.setText("Street");

        CityLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CityLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CityLbl.setText("City");

        StateLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StateLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        StateLbl.setText("Street");

        ZipcodeLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ZipcodeLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ZipcodeLbl.setText("Zipcode");

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ZipcodeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(StateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(SaveBtn)
                                .addGap(0, 139, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ZipcodeTxtFld, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(StateTxtFld)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CityLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StreetLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StreetTxtFld)
                            .addComponent(CityTxtFld))))
                .addGap(21, 21, 21))
            .addComponent(AddressTitleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(AddressTitleLbl)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StreetLbl)
                    .addComponent(StreetTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityLbl)
                    .addComponent(CityTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StateLbl)
                    .addComponent(StateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZipcodeLbl)
                    .addComponent(ZipcodeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(SaveBtn)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        address.setStreatAdrss(StreetTxtFld.getText());
        address.setCity(CityTxtFld.getText());
        address.setState(StateTxtFld.getText());
        address.setZipcode(ZipcodeTxtFld.getText());
        person.setAddressinfovar(address);
        JOptionPane.showMessageDialog(this, "Address is saved");
    }//GEN-LAST:event_SaveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressTitleLbl;
    private javax.swing.JLabel CityLbl;
    private javax.swing.JTextField CityTxtFld;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel StateLbl;
    private javax.swing.JTextField StateTxtFld;
    private javax.swing.JLabel StreetLbl;
    private javax.swing.JTextField StreetTxtFld;
    private javax.swing.JLabel ZipcodeLbl;
    private javax.swing.JTextField ZipcodeTxtFld;
    // End of variables declaration//GEN-END:variables
}
