/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.BankDetails;
import model.Person;

/**
 *
 * @author nisar
 */
public class CheckingAccCVJpanel extends javax.swing.JPanel {

    BankDetails bank;
    Person person;
    public CheckingAccCVJpanel(BankDetails bank,Person person) {
        initComponents();
        this.bank = bank;
        this.person = person;
    }

    /*CheckingAccCVJpanel() {
    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPanel = new javax.swing.JSplitPane();
        ControlPanel = new javax.swing.JPanel();
        ChekCreateBtn = new javax.swing.JButton();
        ChekCreatBtn = new javax.swing.JButton();
        WorkSpace = new javax.swing.JPanel();

        ChekCreateBtn.setText("Create");
        ChekCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChekCreateBtnActionPerformed(evt);
            }
        });

        ChekCreatBtn.setText("View");
        ChekCreatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChekCreatBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChekCreateBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ChekCreatBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(ChekCreateBtn)
                .addGap(18, 18, 18)
                .addComponent(ChekCreatBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SplitPanel.setLeftComponent(ControlPanel);

        javax.swing.GroupLayout WorkSpaceLayout = new javax.swing.GroupLayout(WorkSpace);
        WorkSpace.setLayout(WorkSpaceLayout);
        WorkSpaceLayout.setHorizontalGroup(
            WorkSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        WorkSpaceLayout.setVerticalGroup(
            WorkSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        SplitPanel.setRightComponent(WorkSpace);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ChekCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChekCreateBtnActionPerformed
       CheckingAccInfoCreateJpanel createpanel=new CheckingAccInfoCreateJpanel(bank,person);
       SplitPanel.setRightComponent(createpanel);
    }//GEN-LAST:event_ChekCreateBtnActionPerformed

    private void ChekCreatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChekCreatBtnActionPerformed
       CheckingAccInfoViewJpanel viewpanel=new CheckingAccInfoViewJpanel(bank);
       SplitPanel.setRightComponent(viewpanel);
    }//GEN-LAST:event_ChekCreatBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChekCreatBtn;
    private javax.swing.JButton ChekCreateBtn;
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JSplitPane SplitPanel;
    private javax.swing.JPanel WorkSpace;
    // End of variables declaration//GEN-END:variables
}
