/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.BankDetails;
import model.Person;

/**
 *
 * @author nisar
 */
public class CheckingAccInfoCreateJpanel extends javax.swing.JPanel {

    BankDetails bank;
    Person person;
    public CheckingAccInfoCreateJpanel(BankDetails bank,Person person) {
        initComponents();
        this.bank = bank;
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLbl = new javax.swing.JLabel();
        BnameLbl = new javax.swing.JLabel();
        RtngNoBtn = new javax.swing.JLabel();
        AccNoLbl = new javax.swing.JLabel();
        AccNumTxtFld = new javax.swing.JTextField();
        BNameTxtFld = new javax.swing.JTextField();
        RtNoTxtFld = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();

        TitleLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLbl.setText("Checking Bank Details");

        BnameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BnameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BnameLbl.setText("Bank Name");

        RtngNoBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RtngNoBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RtngNoBtn.setText("Routing Number ");

        AccNoLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AccNoLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AccNoLbl.setText("Account Number");

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TitleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RtngNoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaveBtn)
                    .addComponent(BNameTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(RtNoTxtFld)
                    .addComponent(AccNumTxtFld))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AccNoLbl, BnameLbl, RtngNoBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLbl)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BnameLbl)
                    .addComponent(BNameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RtngNoBtn)
                    .addComponent(RtNoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccNoLbl)
                    .addComponent(AccNumTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaveBtn)
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        
        bank.setCBname(BNameTxtFld.getText());
        
        bank.setCBRountingNo(RtNoTxtFld.getText());
        bank.setCBAccNo(AccNumTxtFld.getText());
        person.setBankdetailsvar(bank);
        JOptionPane.showMessageDialog(this, "saved successfully");
    }//GEN-LAST:event_SaveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccNoLbl;
    private javax.swing.JTextField AccNumTxtFld;
    private javax.swing.JTextField BNameTxtFld;
    private javax.swing.JLabel BnameLbl;
    private javax.swing.JTextField RtNoTxtFld;
    private javax.swing.JLabel RtngNoBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel TitleLbl;
    // End of variables declaration//GEN-END:variables
}
