/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.BankDetails;

/**
 *
 * @author nisar
 */
public class CheckingAccInfoViewJpanel extends javax.swing.JPanel {

    BankDetails bank;
    public CheckingAccInfoViewJpanel(BankDetails bank) {
        initComponents();
        this.bank = bank;
        displayProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLbl = new javax.swing.JLabel();
        BnameLbl = new javax.swing.JLabel();
        RtngNoBtn = new javax.swing.JLabel();
        AccNoLbl = new javax.swing.JLabel();
        AccNumTxtFld = new javax.swing.JTextField();
        BNameTxtFld = new javax.swing.JTextField();
        RtNoTxtFld = new javax.swing.JTextField();

        TitleLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLbl.setText("Checking Bank Details");

        BnameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BnameLbl.setText("Bank Name");

        RtngNoBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RtngNoBtn.setText("Routing Number ");

        AccNoLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AccNoLbl.setText("Account Number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(AccNoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RtngNoBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(BnameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BNameTxtFld)
                    .addComponent(RtNoTxtFld)
                    .addComponent(AccNumTxtFld))
                .addContainerGap())
            .addComponent(TitleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(TitleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BnameLbl)
                    .addComponent(BNameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RtngNoBtn)
                    .addComponent(RtNoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccNoLbl)
                    .addComponent(AccNumTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccNoLbl;
    private javax.swing.JTextField AccNumTxtFld;
    private javax.swing.JTextField BNameTxtFld;
    private javax.swing.JLabel BnameLbl;
    private javax.swing.JTextField RtNoTxtFld;
    private javax.swing.JLabel RtngNoBtn;
    private javax.swing.JLabel TitleLbl;
    // End of variables declaration//GEN-END:variables

private void displayProduct() {
        BNameTxtFld.setText(bank.getCBname());
        RtNoTxtFld.setText(bank.getCBRountingNo());
        AccNumTxtFld.setText(bank.getCBAccNo());
}
}
