/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.DemographicInfo;
import model.Person;


/**
 *
 * @author nisar
 */
public class DemographicCvJpanel extends javax.swing.JPanel {

    DemographicInfo demographic;
    Person person;
    public DemographicCvJpanel(DemographicInfo demographic,Person person) {
        initComponents();
        this.demographic = demographic;
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPanel = new javax.swing.JSplitPane();
        ControlPanel = new javax.swing.JPanel();
        DemoCreateBtn = new javax.swing.JButton();
        DemoViewBtn = new javax.swing.JButton();
        WorkSpace = new javax.swing.JPanel();

        DemoCreateBtn.setText("Create");
        DemoCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemoCreateBtnActionPerformed(evt);
            }
        });

        DemoViewBtn.setText("View");
        DemoViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemoViewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DemoCreateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(DemoViewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                .addContainerGap())
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(DemoCreateBtn)
                .addGap(18, 18, 18)
                .addComponent(DemoViewBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SplitPanel.setLeftComponent(ControlPanel);

        javax.swing.GroupLayout WorkSpaceLayout = new javax.swing.GroupLayout(WorkSpace);
        WorkSpace.setLayout(WorkSpaceLayout);
        WorkSpaceLayout.setHorizontalGroup(
            WorkSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        WorkSpaceLayout.setVerticalGroup(
            WorkSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        SplitPanel.setRightComponent(WorkSpace);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DemoCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemoCreateBtnActionPerformed
       DemographicInfoCreateJpanel createpanel=new DemographicInfoCreateJpanel(demographic,person);
       SplitPanel.setRightComponent(createpanel);
    }//GEN-LAST:event_DemoCreateBtnActionPerformed

    private void DemoViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemoViewBtnActionPerformed
       DemographicInfoViewJpanel viewpanel=new DemographicInfoViewJpanel(demographic);
       SplitPanel.setRightComponent(viewpanel);
    }//GEN-LAST:event_DemoViewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JButton DemoCreateBtn;
    private javax.swing.JButton DemoViewBtn;
    private javax.swing.JSplitPane SplitPanel;
    private javax.swing.JPanel WorkSpace;
    // End of variables declaration//GEN-END:variables
}
