/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.DemographicInfo;

/**
 *
 * @author nisar
 */
public class DemographicInfoViewJpanel extends javax.swing.JPanel {

    DemographicInfo demographic;
    public DemographicInfoViewJpanel(DemographicInfo demographic) {
        initComponents();
        this.demographic = demographic;
        displayProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DemoTitleLbl = new javax.swing.JLabel();
        FrstNameLbl = new javax.swing.JLabel();
        LstNameLbl = new javax.swing.JLabel();
        DOBLbl = new javax.swing.JLabel();
        AgeLbl = new javax.swing.JLabel();
        WghtLbl = new javax.swing.JLabel();
        HghtLbl = new javax.swing.JLabel();
        PhnoLbl = new javax.swing.JLabel();
        SSNLbl = new javax.swing.JLabel();
        FrstNmTxtFld = new javax.swing.JTextField();
        PhnoTxtFld = new javax.swing.JTextField();
        LstNmTxtFld = new javax.swing.JTextField();
        DOBTxtFld = new javax.swing.JTextField();
        WghtTxtFld = new javax.swing.JTextField();
        AgeTxtFld = new javax.swing.JTextField();
        HghtTxtFld = new javax.swing.JTextField();
        SSNTxtFld = new javax.swing.JTextField();

        DemoTitleLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DemoTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DemoTitleLbl.setText("Demographic Info");

        FrstNameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FrstNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FrstNameLbl.setText("First Name");

        LstNameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LstNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LstNameLbl.setText("Last Name");

        DOBLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DOBLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DOBLbl.setText("Date Of Birth");

        AgeLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AgeLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AgeLbl.setText("Age");

        WghtLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        WghtLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        WghtLbl.setText("Weight");

        HghtLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HghtLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        HghtLbl.setText("Height");

        PhnoLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PhnoLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PhnoLbl.setText("Phone no");

        SSNLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SSNLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SSNLbl.setText("Social Scurity Number");

        FrstNmTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrstNmTxtFldActionPerformed(evt);
            }
        });

        PhnoTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhnoTxtFldActionPerformed(evt);
            }
        });

        LstNmTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LstNmTxtFldActionPerformed(evt);
            }
        });

        DOBTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBTxtFldActionPerformed(evt);
            }
        });

        WghtTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WghtTxtFldActionPerformed(evt);
            }
        });

        AgeTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeTxtFldActionPerformed(evt);
            }
        });

        HghtTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HghtTxtFldActionPerformed(evt);
            }
        });

        SSNTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSNTxtFldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LstNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FrstNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AgeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FrstNmTxtFld)
                                    .addComponent(AgeTxtFld)
                                    .addComponent(WghtTxtFld)
                                    .addComponent(HghtTxtFld)
                                    .addComponent(LstNmTxtFld)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PhnoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WghtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SSNLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SSNTxtFld)
                                    .addComponent(PhnoTxtFld)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DOBLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DOBTxtFld)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(HghtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(430, 430, 430))))
            .addComponent(DemoTitleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AgeLbl, DOBLbl, FrstNameLbl, HghtLbl, LstNameLbl, PhnoLbl, SSNLbl, WghtLbl});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DemoTitleLbl)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FrstNameLbl)
                    .addComponent(FrstNmTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LstNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LstNmTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOBLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOBTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLbl)
                    .addComponent(AgeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WghtLbl)
                    .addComponent(WghtTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HghtTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HghtLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhnoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhnoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SSNLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSNTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AgeLbl, DOBLbl, FrstNameLbl, HghtLbl, LstNameLbl, PhnoLbl, SSNLbl, WghtLbl});

    }// </editor-fold>//GEN-END:initComponents

    private void FrstNmTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrstNmTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FrstNmTxtFldActionPerformed

    private void PhnoTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhnoTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhnoTxtFldActionPerformed

    private void LstNmTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LstNmTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LstNmTxtFldActionPerformed

    private void DOBTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBTxtFldActionPerformed

    private void WghtTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WghtTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WghtTxtFldActionPerformed

    private void AgeTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeTxtFldActionPerformed

    private void HghtTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HghtTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HghtTxtFldActionPerformed

    private void SSNTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSNTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSNTxtFldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLbl;
    private javax.swing.JTextField AgeTxtFld;
    private javax.swing.JLabel DOBLbl;
    private javax.swing.JTextField DOBTxtFld;
    private javax.swing.JLabel DemoTitleLbl;
    private javax.swing.JLabel FrstNameLbl;
    private javax.swing.JTextField FrstNmTxtFld;
    private javax.swing.JLabel HghtLbl;
    private javax.swing.JTextField HghtTxtFld;
    private javax.swing.JLabel LstNameLbl;
    private javax.swing.JTextField LstNmTxtFld;
    private javax.swing.JLabel PhnoLbl;
    private javax.swing.JTextField PhnoTxtFld;
    private javax.swing.JLabel SSNLbl;
    private javax.swing.JTextField SSNTxtFld;
    private javax.swing.JLabel WghtLbl;
    private javax.swing.JTextField WghtTxtFld;
    // End of variables declaration//GEN-END:variables
private void displayProduct() {
        FrstNmTxtFld.setText(demographic.getFirstName());
        LstNmTxtFld.setText(demographic.getLastName());
        PhnoTxtFld.setText(demographic.getPhno());
        DOBTxtFld.setText(demographic.getDOB());
        WghtTxtFld.setText(demographic.getWeight());
        HghtTxtFld.setText(demographic.getHeight());
        SSNTxtFld.setText(demographic.getSSN());
        AgeTxtFld.setText(demographic.getAge());
    
    
    }

}
