/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.DemographicInfo;
import model.Person;

/**
 *
 * @author nisar
 */
public class DemographicInfoCreateJpanel extends javax.swing.JPanel {

    DemographicInfo demographic;
    Person person;
    public DemographicInfoCreateJpanel(DemographicInfo demographic,Person person) {
        initComponents();
        this.demographic=demographic;
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        DemoTitleLbl = new javax.swing.JLabel();
        FrstNameLbl = new javax.swing.JLabel();
        LstNameLbl = new javax.swing.JLabel();
        DOBLbl = new javax.swing.JLabel();
        AgeLbl = new javax.swing.JLabel();
        WghtLbl = new javax.swing.JLabel();
        HghtLbl = new javax.swing.JLabel();
        PhnoLbl = new javax.swing.JLabel();
        SSNLbl = new javax.swing.JLabel();
        FrstNmTxtFld = new javax.swing.JTextField();
        PhnoTxtFld = new javax.swing.JTextField();
        LstNmTxtFld = new javax.swing.JTextField();
        DOBTxtFld = new javax.swing.JTextField();
        WghtTxtFld = new javax.swing.JTextField();
        AgeTxtFld = new javax.swing.JTextField();
        HghtTxtFld = new javax.swing.JTextField();
        SSNTxtFld = new javax.swing.JTextField();
        SaveDemoBtn = new javax.swing.JButton();

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        DemoTitleLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DemoTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DemoTitleLbl.setText("Demographic Info");

        FrstNameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FrstNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FrstNameLbl.setText("First Name");

        LstNameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LstNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LstNameLbl.setText("Last Name");

        DOBLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DOBLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DOBLbl.setText("Date Of Birth");

        AgeLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AgeLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AgeLbl.setText("Age");

        WghtLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        WghtLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        WghtLbl.setText("Weight");

        HghtLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HghtLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        HghtLbl.setText("Height");

        PhnoLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PhnoLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PhnoLbl.setText("Phone no");

        SSNLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SSNLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SSNLbl.setText("Social Scurity Number");

        FrstNmTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrstNmTxtFldActionPerformed(evt);
            }
        });

        PhnoTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhnoTxtFldActionPerformed(evt);
            }
        });

        LstNmTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LstNmTxtFldActionPerformed(evt);
            }
        });

        DOBTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBTxtFldActionPerformed(evt);
            }
        });

        WghtTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WghtTxtFldActionPerformed(evt);
            }
        });

        AgeTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeTxtFldActionPerformed(evt);
            }
        });

        HghtTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HghtTxtFldActionPerformed(evt);
            }
        });

        SSNTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSNTxtFldActionPerformed(evt);
            }
        });

        SaveDemoBtn.setText("Save");
        SaveDemoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveDemoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HghtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WghtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhnoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhnoTxtFld)
                            .addComponent(WghtTxtFld)
                            .addComponent(HghtTxtFld)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SSNLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SaveDemoBtn)
                            .addComponent(SSNTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LstNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FrstNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FrstNmTxtFld)
                            .addComponent(LstNmTxtFld)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DOBLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AgeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DOBTxtFld)
                            .addComponent(AgeTxtFld))))
                .addContainerGap())
            .addComponent(DemoTitleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AgeLbl, DOBLbl, FrstNameLbl, HghtLbl, LstNameLbl, PhnoLbl, SSNLbl, WghtLbl});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(DemoTitleLbl)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FrstNameLbl)
                    .addComponent(FrstNmTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LstNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LstNmTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOBLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOBTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLbl)
                    .addComponent(AgeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HghtLbl)
                    .addComponent(HghtTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WghtLbl)
                    .addComponent(WghtTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhnoLbl)
                    .addComponent(PhnoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SSNTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSNLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaveDemoBtn)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AgeLbl, DOBLbl, FrstNameLbl, HghtLbl, LstNameLbl, PhnoLbl, SSNLbl, WghtLbl});

    }// </editor-fold>//GEN-END:initComponents

    private void FrstNmTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrstNmTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FrstNmTxtFldActionPerformed

    private void PhnoTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhnoTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhnoTxtFldActionPerformed

    private void LstNmTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LstNmTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LstNmTxtFldActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void DOBTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBTxtFldActionPerformed

    private void WghtTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WghtTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WghtTxtFldActionPerformed

    private void AgeTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeTxtFldActionPerformed

    private void HghtTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HghtTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HghtTxtFldActionPerformed

    private void SSNTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSNTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSNTxtFldActionPerformed

    private void SaveDemoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveDemoBtnActionPerformed
        demographic.setFirstName(FrstNmTxtFld.getText());
        demographic.setLastName(LstNmTxtFld.getText());
        demographic.setDOB(DOBTxtFld.getText());
        demographic.setPhno(PhnoTxtFld.getText());
        demographic.setHeight(HghtTxtFld.getText());
        demographic.setWeight(WghtTxtFld.getText());
        demographic.setAge(AgeTxtFld.getText());
        demographic.setSSN(SSNTxtFld.getText());
        person.setDemographicinfovar(demographic);
        JOptionPane.showMessageDialog(this, "saved successfully");
    }//GEN-LAST:event_SaveDemoBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLbl;
    private javax.swing.JTextField AgeTxtFld;
    private javax.swing.JLabel DOBLbl;
    private javax.swing.JTextField DOBTxtFld;
    private javax.swing.JLabel DemoTitleLbl;
    private javax.swing.JLabel FrstNameLbl;
    private javax.swing.JTextField FrstNmTxtFld;
    private javax.swing.JLabel HghtLbl;
    private javax.swing.JTextField HghtTxtFld;
    private javax.swing.JLabel LstNameLbl;
    private javax.swing.JTextField LstNmTxtFld;
    private javax.swing.JLabel PhnoLbl;
    private javax.swing.JTextField PhnoTxtFld;
    private javax.swing.JLabel SSNLbl;
    private javax.swing.JTextField SSNTxtFld;
    private javax.swing.JButton SaveDemoBtn;
    private javax.swing.JLabel WghtLbl;
    private javax.swing.JTextField WghtTxtFld;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
