/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.DriverLicInfo;
import model.Person;


public class DriverLicCreateJpanel extends javax.swing.JPanel {

    DriverLicInfo license;
    Person person;
    String AbsPath;
    public DriverLicCreateJpanel(DriverLicInfo license,Person person) {
        initComponents();
        this.license = license;
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleBtn = new javax.swing.JLabel();
        DOILbl = new javax.swing.JLabel();
        DOELbl = new javax.swing.JLabel();
        LicNoLbl = new javax.swing.JLabel();
        LicNoTxtFld = new javax.swing.JTextField();
        DOITxtFld = new javax.swing.JTextField();
        DOETxtFLd = new javax.swing.JTextField();
        PicTxtFld = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        BldTypeTxtFld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        picturebtn = new javax.swing.JButton();

        TitleBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TitleBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleBtn.setText("Driver License Info");

        DOILbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DOILbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DOILbl.setText("Date of Issurance");

        DOELbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DOELbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DOELbl.setText("Date of Expiry");

        LicNoLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LicNoLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LicNoLbl.setText("License number");

        LicNoTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LicNoTxtFldActionPerformed(evt);
            }
        });

        DOITxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOITxtFldActionPerformed(evt);
            }
        });

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        BldTypeTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BldTypeTxtFldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Blood Type");

        picturebtn.setText("upload picture");
        picturebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picturebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TitleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LicNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DOELbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DOILbl, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(picturebtn, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SaveBtn)
                                .addGap(0, 73, Short.MAX_VALUE))
                            .addComponent(LicNoTxtFld)
                            .addComponent(DOITxtFld)
                            .addComponent(DOETxtFLd, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PicTxtFld)
                            .addComponent(BldTypeTxtFld))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LicNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LicNoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOILbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOITxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOELbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOETxtFLd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PicTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(picturebtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BldTypeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SaveBtn)
                .addGap(0, 70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LicNoTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LicNoTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LicNoTxtFldActionPerformed

    private void DOITxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOITxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOITxtFldActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        license.setLicNo(LicNoTxtFld.getText());
        license.setIssuedDate(DOITxtFld.getText());
        license.setExpireyDate(DOETxtFLd.getText());
        license.setBloodType(BldTypeTxtFld.getText());
        license.setPicture(PicTxtFld.getText());
        person.setDriverlicensevar(license);
        JOptionPane.showMessageDialog(this, "saved successfully");
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void BldTypeTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BldTypeTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BldTypeTxtFldActionPerformed

    private void picturebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picturebtnActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result ==  JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            AbsPath = selectedFile.getAbsolutePath();
            PicTxtFld.setText(AbsPath);
        }
    }//GEN-LAST:event_picturebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BldTypeTxtFld;
    private javax.swing.JLabel DOELbl;
    private javax.swing.JTextField DOETxtFLd;
    private javax.swing.JLabel DOILbl;
    private javax.swing.JTextField DOITxtFld;
    private javax.swing.JLabel LicNoLbl;
    private javax.swing.JTextField LicNoTxtFld;
    private javax.swing.JTextField PicTxtFld;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel TitleBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton picturebtn;
    // End of variables declaration//GEN-END:variables
}
