/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.DriverLicInfo;
import model.Person;

/**
 *
 * @author nisar
 */
public class DriverLicCVJpanel extends javax.swing.JPanel {

    DriverLicInfo license;
    Person person;
    public DriverLicCVJpanel(DriverLicInfo license,Person person) {
        initComponents();
        this.license = license;
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPanel = new javax.swing.JSplitPane();
        ControlPanel = new javax.swing.JPanel();
        DrivCreateBtn = new javax.swing.JButton();
        DrivViewBtn = new javax.swing.JButton();
        WorkSpace = new javax.swing.JPanel();

        DrivCreateBtn.setText("Create");
        DrivCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrivCreateBtnActionPerformed(evt);
            }
        });

        DrivViewBtn.setText("View");
        DrivViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrivViewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DrivCreateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(DrivViewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(DrivCreateBtn)
                .addGap(18, 18, 18)
                .addComponent(DrivViewBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SplitPanel.setLeftComponent(ControlPanel);

        javax.swing.GroupLayout WorkSpaceLayout = new javax.swing.GroupLayout(WorkSpace);
        WorkSpace.setLayout(WorkSpaceLayout);
        WorkSpaceLayout.setHorizontalGroup(
            WorkSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        WorkSpaceLayout.setVerticalGroup(
            WorkSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        SplitPanel.setRightComponent(WorkSpace);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DrivCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrivCreateBtnActionPerformed
        DriverLicCreateJpanel createpanel=new DriverLicCreateJpanel(license,person);
        SplitPanel.setRightComponent(createpanel);
    }//GEN-LAST:event_DrivCreateBtnActionPerformed

    private void DrivViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrivViewBtnActionPerformed
      DriverLicViewJpanel viewpanel=new DriverLicViewJpanel(license);
      SplitPanel.setRightComponent(viewpanel);  
    }//GEN-LAST:event_DrivViewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JButton DrivCreateBtn;
    private javax.swing.JButton DrivViewBtn;
    private javax.swing.JSplitPane SplitPanel;
    private javax.swing.JPanel WorkSpace;
    // End of variables declaration//GEN-END:variables
}
