/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.AddressInfo;
import model.CheckingAccInfo;
import model.DemographicInfo;
import model.DriverLicInfo;
import model.MedicalRec;
import model.BankDetails;
import model.Person;

/**
 *
 * @author nisar
 */
public class MainFrame extends javax.swing.JFrame {

        Person person;
        AddressInfo address;
        DemographicInfo demographic;
        BankDetails checkingacc;
        CheckingAccInfo savingacc;
        MedicalRec medicalrec;
        DriverLicInfo driverlic;
    public MainFrame() {
        initComponents();
        person = new Person();
        address =new AddressInfo();
        demographic =new DemographicInfo();
        checkingacc=new BankDetails();
       savingacc =new CheckingAccInfo();
        medicalrec =new MedicalRec();
        driverlic =new DriverLicInfo();
        person.addressinfovar = new AddressInfo();
        person.demographicinfovar = new DemographicInfo();
        person.medicalinfovar = new MedicalRec();
        person.driverlicensevar = new DriverLicInfo();
        person.bankdetailsvar = new BankDetails();
        person.savingsvar = new CheckingAccInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        SplitPanel = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        DemoGrfJbtn = new javax.swing.JButton();
        ReportJbtn = new javax.swing.JButton();
        MedRecJbtn = new javax.swing.JButton();
        DrvrLicJbtn = new javax.swing.JButton();
        SvngAccJbtn = new javax.swing.JButton();
        AdrssJbtn = new javax.swing.JButton();
        CheckingsBankbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jButton6.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DemoGrfJbtn.setText("Demographic");
        DemoGrfJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemoGrfJbtnActionPerformed(evt);
            }
        });

        ReportJbtn.setText("View Report");
        ReportJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportJbtnActionPerformed(evt);
            }
        });

        MedRecJbtn.setText("Medical Record");
        MedRecJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedRecJbtnActionPerformed(evt);
            }
        });

        DrvrLicJbtn.setText("Driver License");
        DrvrLicJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrvrLicJbtnActionPerformed(evt);
            }
        });

        SvngAccJbtn.setText("Savings Bank");
        SvngAccJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SvngAccJbtnActionPerformed(evt);
            }
        });

        AdrssJbtn.setText("Address");
        AdrssJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdrssJbtnActionPerformed(evt);
            }
        });

        CheckingsBankbtn.setText("Checkings Bank");
        CheckingsBankbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckingsBankbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ReportJbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MedRecJbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DrvrLicJbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CheckingsBankbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(SvngAccJbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdrssJbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DemoGrfJbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(DemoGrfJbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdrssJbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SvngAccJbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckingsBankbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DrvrLicJbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MedRecJbtn)
                .addGap(18, 18, 18)
                .addComponent(ReportJbtn)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        SplitPanel.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
        );

        SplitPanel.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DemoGrfJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemoGrfJbtnActionPerformed
        DemographicCvJpanel demographicpanel = new DemographicCvJpanel(demographic,person);
        SplitPanel.setRightComponent(demographicpanel);
    }//GEN-LAST:event_DemoGrfJbtnActionPerformed

    private void AdrssJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdrssJbtnActionPerformed
        AddressCVJpanel addresspanel = new AddressCVJpanel(address,person);
        SplitPanel.setRightComponent(addresspanel);
    }//GEN-LAST:event_AdrssJbtnActionPerformed

    private void SvngAccJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SvngAccJbtnActionPerformed
        SavingInfoCVJpanel savingpanel= new SavingInfoCVJpanel(savingacc,person);
        SplitPanel.setRightComponent(savingpanel);
    }//GEN-LAST:event_SvngAccJbtnActionPerformed

    private void DrvrLicJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrvrLicJbtnActionPerformed
        DriverLicCVJpanel licensepanel= new DriverLicCVJpanel(driverlic,person);
        SplitPanel.setRightComponent(licensepanel);
    }//GEN-LAST:event_DrvrLicJbtnActionPerformed

    private void MedRecJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedRecJbtnActionPerformed
        MedicalRecCVJpanel licensepanel= new MedicalRecCVJpanel(medicalrec,person);
        SplitPanel.setRightComponent(licensepanel);
    }//GEN-LAST:event_MedRecJbtnActionPerformed

    private void ReportJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportJbtnActionPerformed
        // TODO add your handling code here:
        ViewEntire viewentire = new ViewEntire(person);
        SplitPanel.setRightComponent(viewentire);
    }//GEN-LAST:event_ReportJbtnActionPerformed

    private void CheckingsBankbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckingsBankbtnActionPerformed
        // TODO add your handling code here:
       CheckingAccCVJpanel savingsPanel = new CheckingAccCVJpanel(checkingacc,person);
        SplitPanel.setRightComponent(savingsPanel);
    }//GEN-LAST:event_CheckingsBankbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdrssJbtn;
    private javax.swing.JButton CheckingsBankbtn;
    private javax.swing.JButton DemoGrfJbtn;
    private javax.swing.JButton DrvrLicJbtn;
    private javax.swing.JButton MedRecJbtn;
    private javax.swing.JButton ReportJbtn;
    private javax.swing.JSplitPane SplitPanel;
    private javax.swing.JButton SvngAccJbtn;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
