/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.MedicalRec;

/**
 *
 * @author nisar
 */
public class MedicalRecViewJpanel extends javax.swing.JPanel {

    MedicalRec medical;
    public MedicalRecViewJpanel(MedicalRec medical) {
        initComponents();
        this.medical= medical;
         displayProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        MedRecNoLbl = new javax.swing.JLabel();
        Alrgy1Lbl = new javax.swing.JLabel();
        Alrgy3Lbl = new javax.swing.JLabel();
        Alrgy2Lbl = new javax.swing.JLabel();
        MedRecNoTxtFld = new javax.swing.JTextField();
        Alrgy3TxtFld = new javax.swing.JTextField();
        AlrgyTxtFld = new javax.swing.JTextField();
        Alrgy2TxtFld = new javax.swing.JTextField();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Medical Record");

        MedRecNoLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MedRecNoLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MedRecNoLbl.setText("Medical Record Number");

        Alrgy1Lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Alrgy1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Alrgy1Lbl.setText("Allergy 1");

        Alrgy3Lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Alrgy3Lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Alrgy3Lbl.setText("Allergy 3");

        Alrgy2Lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Alrgy2Lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Alrgy2Lbl.setText("Allergy 2");

        MedRecNoTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedRecNoTxtFldActionPerformed(evt);
            }
        });

        Alrgy3TxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alrgy3TxtFldActionPerformed(evt);
            }
        });

        AlrgyTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlrgyTxtFldActionPerformed(evt);
            }
        });

        Alrgy2TxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alrgy2TxtFldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Alrgy1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Alrgy2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AlrgyTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                            .addComponent(Alrgy2TxtFld)
                            .addComponent(Alrgy3TxtFld)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MedRecNoLbl)
                                .addGap(57, 57, 57)
                                .addComponent(MedRecNoTxtFld)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Alrgy3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Alrgy1Lbl, Alrgy2Lbl, Alrgy3Lbl, MedRecNoLbl});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedRecNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MedRecNoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alrgy1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlrgyTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alrgy2TxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alrgy2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alrgy3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alrgy3TxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Alrgy1Lbl, Alrgy2Lbl, Alrgy3Lbl, MedRecNoLbl});

    }// </editor-fold>//GEN-END:initComponents

    private void MedRecNoTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedRecNoTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedRecNoTxtFldActionPerformed

    private void Alrgy3TxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alrgy3TxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Alrgy3TxtFldActionPerformed

    private void AlrgyTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlrgyTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlrgyTxtFldActionPerformed

    private void Alrgy2TxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alrgy2TxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Alrgy2TxtFldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alrgy1Lbl;
    private javax.swing.JLabel Alrgy2Lbl;
    private javax.swing.JTextField Alrgy2TxtFld;
    private javax.swing.JLabel Alrgy3Lbl;
    private javax.swing.JTextField Alrgy3TxtFld;
    private javax.swing.JTextField AlrgyTxtFld;
    private javax.swing.JLabel MedRecNoLbl;
    private javax.swing.JTextField MedRecNoTxtFld;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

private void displayProduct() {
        MedRecNoTxtFld.setText(medical.getMedRecordNo());
        AlrgyTxtFld.setText(medical.getAlergy1());
        Alrgy2TxtFld.setText(medical.getAlergy2());
        Alrgy3TxtFld.setText(medical.getAlergy3());
}
}
