/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.CheckingAccInfo;
import model.Person;

/**
 *
 * @author nisar
 */
public class SavingAccInfoCreateJpanel extends javax.swing.JPanel {

    CheckingAccInfo checking;
    Person person;
    public SavingAccInfoCreateJpanel(CheckingAccInfo checking,Person person) {
        initComponents();
        this.checking=checking;
        this.person=person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BnameLbl2 = new javax.swing.JLabel();
        BnameLbl3 = new javax.swing.JLabel();
        AccLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AccNumTxtLbl1 = new javax.swing.JTextField();
        BNameTxtFld1 = new javax.swing.JTextField();
        RtNoTxtLbl1 = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();

        BnameLbl2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BnameLbl2.setText("Bank Name");

        BnameLbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BnameLbl3.setText("Routing Number ");

        AccLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AccLbl.setText("Account Number");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Saving Account Details");

        AccNumTxtLbl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccNumTxtLbl1ActionPerformed(evt);
            }
        });

        BNameTxtFld1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNameTxtFld1ActionPerformed(evt);
            }
        });

        RtNoTxtLbl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RtNoTxtLbl1ActionPerformed(evt);
            }
        });

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BnameLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(BnameLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AccLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SaveBtn)
                        .addGap(0, 181, Short.MAX_VALUE))
                    .addComponent(BNameTxtFld1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RtNoTxtLbl1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AccNumTxtLbl1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BnameLbl2)
                    .addComponent(BNameTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RtNoTxtLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BnameLbl3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccLbl)
                    .addComponent(AccNumTxtLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(SaveBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BNameTxtFld1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNameTxtFld1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BNameTxtFld1ActionPerformed

    private void RtNoTxtLbl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RtNoTxtLbl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RtNoTxtLbl1ActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        checking.setBname(BNameTxtFld1.getText());
        
        checking.setBRountingNo(RtNoTxtLbl1.getText());
        checking.setBAccNo(AccNumTxtLbl1.getText());
        person.setSavingsvar(checking);
        JOptionPane.showMessageDialog(this,"Saved successfully");
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void AccNumTxtLbl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccNumTxtLbl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccNumTxtLbl1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccLbl;
    private javax.swing.JTextField AccNumTxtLbl1;
    private javax.swing.JTextField BNameTxtFld1;
    private javax.swing.JLabel BnameLbl2;
    private javax.swing.JLabel BnameLbl3;
    private javax.swing.JTextField RtNoTxtLbl1;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
