/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.CheckingAccInfo;

/**
 *
 * @author nisar
 */
public class SavingAccInfoViewJpanel extends javax.swing.JPanel {

    CheckingAccInfo saving;
    
    public SavingAccInfoViewJpanel(CheckingAccInfo saving) {
        initComponents();
        this.saving = saving;
        displayProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BnameLbl2 = new javax.swing.JLabel();
        BnameLbl3 = new javax.swing.JLabel();
        AccLbl = new javax.swing.JLabel();
        AccNumTxtLbl1 = new javax.swing.JTextField();
        BNameTxtFld1 = new javax.swing.JTextField();
        RtNoTxtLbl1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Saving Account Details");

        BnameLbl2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BnameLbl2.setText("Bank Name");

        BnameLbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BnameLbl3.setText("Routing Number ");

        AccLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AccLbl.setText("Account Number");

        AccNumTxtLbl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccNumTxtLbl1ActionPerformed(evt);
            }
        });

        BNameTxtFld1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNameTxtFld1ActionPerformed(evt);
            }
        });

        RtNoTxtLbl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RtNoTxtLbl1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Savings Bank Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BnameLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BnameLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AccLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccNumTxtLbl1)
                            .addComponent(RtNoTxtLbl1)
                            .addComponent(BNameTxtFld1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BnameLbl2)
                    .addComponent(BNameTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BnameLbl3)
                    .addComponent(RtNoTxtLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccNumTxtLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccLbl))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AccLbl, BnameLbl2});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AccNumTxtLbl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccNumTxtLbl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccNumTxtLbl1ActionPerformed

    private void BNameTxtFld1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNameTxtFld1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BNameTxtFld1ActionPerformed

    private void RtNoTxtLbl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RtNoTxtLbl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RtNoTxtLbl1ActionPerformed
private void displayProduct() {
        BNameTxtFld1.setText(saving.getBname());
        RtNoTxtLbl1.setText(saving.getBRountingNo());
        AccNumTxtLbl1.setText(saving.getBAccNo());
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccLbl;
    private javax.swing.JTextField AccNumTxtLbl1;
    private javax.swing.JTextField BNameTxtFld1;
    private javax.swing.JLabel BnameLbl2;
    private javax.swing.JLabel BnameLbl3;
    private javax.swing.JTextField RtNoTxtLbl1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
