/*
 * To change this license 

import model.CheckingAheader, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.CheckingAccInfo;
import model.Person;

/**
 *
 * @author nisar
 */
public class SavingInfoCVJpanel extends javax.swing.JPanel {

    CheckingAccInfo saving;
    Person person;
    public SavingInfoCVJpanel(CheckingAccInfo saving,Person person) {
        initComponents();
        this.saving = saving;
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPanel = new javax.swing.JSplitPane();
        ControlPanel = new javax.swing.JPanel();
        SavingCreateBtn = new javax.swing.JButton();
        SavingViewBtn = new javax.swing.JButton();
        WorkSpace = new javax.swing.JPanel();

        SavingCreateBtn.setText("Create");
        SavingCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavingCreateBtnActionPerformed(evt);
            }
        });

        SavingViewBtn.setText("View");
        SavingViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavingViewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SavingCreateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(SavingViewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(SavingCreateBtn)
                .addGap(18, 18, 18)
                .addComponent(SavingViewBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SplitPanel.setLeftComponent(ControlPanel);

        javax.swing.GroupLayout WorkSpaceLayout = new javax.swing.GroupLayout(WorkSpace);
        WorkSpace.setLayout(WorkSpaceLayout);
        WorkSpaceLayout.setHorizontalGroup(
            WorkSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        WorkSpaceLayout.setVerticalGroup(
            WorkSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        SplitPanel.setRightComponent(WorkSpace);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SavingViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavingViewBtnActionPerformed
        SavingAccInfoViewJpanel viewpanel = new SavingAccInfoViewJpanel(saving);
        SplitPanel.setRightComponent(viewpanel);
        
    }//GEN-LAST:event_SavingViewBtnActionPerformed

    private void SavingCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavingCreateBtnActionPerformed
        SavingAccInfoCreateJpanel createpanel = new SavingAccInfoCreateJpanel(saving,person);
        SplitPanel.setRightComponent(createpanel);
    }//GEN-LAST:event_SavingCreateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JButton SavingCreateBtn;
    private javax.swing.JButton SavingViewBtn;
    private javax.swing.JSplitPane SplitPanel;
    private javax.swing.JPanel WorkSpace;
    // End of variables declaration//GEN-END:variables
}
