/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import model.AddressInfo;
import model.BankDetails;
import model.CheckingAccInfo;
import model.DemographicInfo;
import model.DriverLicInfo;
import model.MedicalRec;
import model.Person;

/**
 *
 * @author nisar
 */
public class ViewEntire extends javax.swing.JPanel {

    /**
     * Creates new form ViewEntire
     */
    Person person;
    BufferedImage bufferedImage;
    public ViewEntire(Person person) {
        this.person = person;
        initComponents();
        displayProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblFN = new javax.swing.JLabel();
        lblLN = new javax.swing.JLabel();
        lbldob = new javax.swing.JLabel();
        lblage = new javax.swing.JLabel();
        lblpno = new javax.swing.JLabel();
        lblheight = new javax.swing.JLabel();
        lblweight = new javax.swing.JLabel();
        lblssn = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblstreet = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        lblstate = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblSAbankName = new javax.swing.JLabel();
        lblSAAccNo = new javax.swing.JLabel();
        lblSARoutingNo = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblCHBankname = new javax.swing.JLabel();
        lblCHAccno = new javax.swing.JLabel();
        lblCHRoutingNo = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lbldl = new javax.swing.JLabel();
        lblDOI = new javax.swing.JLabel();
        lblDOE = new javax.swing.JLabel();
        lblBloodGrp = new javax.swing.JLabel();
        lblpicture = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lblrecordNo = new javax.swing.JLabel();
        lblAlergy1 = new javax.swing.JLabel();
        lblAlergy2 = new javax.swing.JLabel();
        lblAlergy3 = new javax.swing.JLabel();
        txtFN = new javax.swing.JTextField();
        txtLN = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtPno = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtStreet = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        txtSABank = new javax.swing.JTextField();
        txtSAAcc = new javax.swing.JTextField();
        txtSARoute = new javax.swing.JTextField();
        txtCHBank = new javax.swing.JTextField();
        txtCHAcc = new javax.swing.JTextField();
        txtCHRoute = new javax.swing.JTextField();
        txtDL = new javax.swing.JTextField();
        txtDOI = new javax.swing.JTextField();
        txtDOE = new javax.swing.JTextField();
        txtBloodGrp = new javax.swing.JTextField();
        txtMedical = new javax.swing.JTextField();
        txtAlergy1 = new javax.swing.JTextField();
        txtAlergy2 = new javax.swing.JTextField();
        txtAlergy3 = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DEMOGRAPHIC IFNORMATION");

        lblFN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFN.setText("FirstName");

        lblLN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLN.setText("LastName");

        lbldob.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldob.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbldob.setText("DOB");

        lblage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblage.setText("Age");

        lblpno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblpno.setText("Phone Number");

        lblheight.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblheight.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblheight.setText("Height");

        lblweight.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblweight.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblweight.setText("Weight");

        lblssn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblssn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblssn.setText("SSN");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ADDRESS");

        lblstreet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblstreet.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblstreet.setText("Street Address");

        lblcity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblcity.setText("City ");

        lblstate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblstate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblstate.setText("State");

        lblZipCode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblZipCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblZipCode.setText("ZIpcode");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("SAVINGS BANK DETAILS");

        lblSAbankName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSAbankName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSAbankName.setText("Bank Name");

        lblSAAccNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSAAccNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSAAccNo.setText("Account Number");

        lblSARoutingNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSARoutingNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSARoutingNo.setText("Routing Number");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("CHECKINGS BANK DETAILS");

        lblCHBankname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCHBankname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCHBankname.setText("Bank Name");

        lblCHAccno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCHAccno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCHAccno.setText("Account Number");

        lblCHRoutingNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCHRoutingNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCHRoutingNo.setText("Routing Number");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("DRIVING LICENSE DETAILS");

        lbldl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbldl.setText("License Number");

        lblDOI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDOI.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDOI.setText("Date Of Issue");

        lblDOE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDOE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDOE.setText("Date of Expiry");

        lblBloodGrp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBloodGrp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBloodGrp.setText("Blood group");

        lblpicture.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpicture.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblpicture.setText("Pictutre");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("MEDICAL RECORDS");

        lblrecordNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblrecordNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblrecordNo.setText("Record Numebr");

        lblAlergy1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAlergy1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAlergy1.setText("Alergy1");

        lblAlergy2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAlergy2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAlergy2.setText("Alergy2");

        lblAlergy3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAlergy3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAlergy3.setText("Alergy3");

        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        txtCHRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCHRouteActionPerformed(evt);
            }
        });

        txtAlergy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlergy1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 151, Short.MAX_VALUE)
                        .addComponent(txtMedical, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFN)
                            .addComponent(lblLN)
                            .addComponent(lbldob)
                            .addComponent(lblage)
                            .addComponent(lblpno)
                            .addComponent(lblheight)
                            .addComponent(lblweight)
                            .addComponent(lblssn)
                            .addComponent(lblstreet)
                            .addComponent(lblcity)
                            .addComponent(lblstate)
                            .addComponent(lblZipCode)
                            .addComponent(lblSAbankName)
                            .addComponent(lblSAAccNo)
                            .addComponent(lblSARoutingNo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCHBankname)
                                    .addComponent(lblCHRoutingNo)
                                    .addComponent(lblCHAccno, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbldl)
                                    .addComponent(lblDOI)
                                    .addComponent(lblrecordNo)
                                    .addComponent(lblAlergy1)
                                    .addComponent(lblAlergy2)
                                    .addComponent(lblAlergy3)
                                    .addComponent(lblDOE)
                                    .addComponent(lblBloodGrp, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblpicture, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCHBank)
                            .addComponent(txtSARoute)
                            .addComponent(txtSAAcc)
                            .addComponent(txtSABank)
                            .addComponent(txtZipCode)
                            .addComponent(txtState)
                            .addComponent(txtCity)
                            .addComponent(txtCHAcc)
                            .addComponent(txtCHRoute)
                            .addComponent(txtDL)
                            .addComponent(txtDOI)
                            .addComponent(txtDOE)
                            .addComponent(txtStreet)
                            .addComponent(txtFN)
                            .addComponent(txtLN)
                            .addComponent(txtDOB)
                            .addComponent(txtAge)
                            .addComponent(txtPno)
                            .addComponent(txtHeight)
                            .addComponent(txtWeight)
                            .addComponent(txtSSN)
                            .addComponent(txtBloodGrp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAlergy1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAlergy2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAlergy3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(55, 55, 55))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAlergy1, lblAlergy2, lblAlergy3, lblBloodGrp, lblCHAccno, lblCHBankname, lblCHRoutingNo, lblDOE, lblDOI, lblFN, lblLN, lblSAAccNo, lblSARoutingNo, lblSAbankName, lblZipCode, lblage, lblcity, lbldl, lbldob, lblheight, lblpicture, lblpno, lblrecordNo, lblssn, lblstate, lblstreet, lblweight});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFN)
                    .addComponent(txtFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLN)
                    .addComponent(txtLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldob)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblage)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpno)
                    .addComponent(txtPno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblheight)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblweight)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblssn)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstreet)
                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstate)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipCode)
                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSAbankName)
                    .addComponent(txtSABank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSAAccNo)
                    .addComponent(txtSAAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSARoutingNo)
                    .addComponent(txtSARoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel21)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCHBankname)
                    .addComponent(txtCHBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCHAccno)
                    .addComponent(txtCHAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCHRoutingNo)
                    .addComponent(txtCHRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldl)
                    .addComponent(txtDL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOI)
                    .addComponent(txtDOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOE)
                    .addComponent(txtDOE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloodGrp)
                    .addComponent(txtBloodGrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpicture)
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblrecordNo)
                    .addComponent(txtMedical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlergy1)
                    .addComponent(txtAlergy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlergy2)
                    .addComponent(txtAlergy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlergy3)
                    .addComponent(txtAlergy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblAlergy1, lblAlergy2, lblAlergy3, lblBloodGrp, lblCHAccno, lblCHBankname, lblCHRoutingNo, lblDOE, lblDOI, lblFN, lblLN, lblSAAccNo, lblSARoutingNo, lblSAbankName, lblZipCode, lblage, lblcity, lbldl, lbldob, lblheight, lblpicture, lblpno, lblrecordNo, lblssn, lblstate, lblstreet, lblweight});

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtCHRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCHRouteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCHRouteActionPerformed

    private void txtAlergy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlergy1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlergy1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlergy1;
    private javax.swing.JLabel lblAlergy2;
    private javax.swing.JLabel lblAlergy3;
    private javax.swing.JLabel lblBloodGrp;
    private javax.swing.JLabel lblCHAccno;
    private javax.swing.JLabel lblCHBankname;
    private javax.swing.JLabel lblCHRoutingNo;
    private javax.swing.JLabel lblDOE;
    private javax.swing.JLabel lblDOI;
    private javax.swing.JLabel lblFN;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLN;
    private javax.swing.JLabel lblSAAccNo;
    private javax.swing.JLabel lblSARoutingNo;
    private javax.swing.JLabel lblSAbankName;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lbldl;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lblheight;
    private javax.swing.JLabel lblpicture;
    private javax.swing.JLabel lblpno;
    private javax.swing.JLabel lblrecordNo;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lblstate;
    private javax.swing.JLabel lblstreet;
    private javax.swing.JLabel lblweight;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAlergy1;
    private javax.swing.JTextField txtAlergy2;
    private javax.swing.JTextField txtAlergy3;
    private javax.swing.JTextField txtBloodGrp;
    private javax.swing.JTextField txtCHAcc;
    private javax.swing.JTextField txtCHBank;
    private javax.swing.JTextField txtCHRoute;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDL;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDOE;
    private javax.swing.JTextField txtDOI;
    private javax.swing.JTextField txtFN;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtLN;
    private javax.swing.JTextField txtMedical;
    private javax.swing.JTextField txtPno;
    private javax.swing.JTextField txtSAAcc;
    private javax.swing.JTextField txtSABank;
    private javax.swing.JTextField txtSARoute;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables

    private void displayProduct() {
       DemographicInfo demographic = person.getDemographicinfovar();
       AddressInfo addres = person.getAddressinfovar();
       BankDetails checkings = person.getBankdetailsvar();
       CheckingAccInfo savings = person.getSavingsvar();
       DriverLicInfo driver = person.getDriverlicensevar();
       MedicalRec medical = person.getMedicalinfovar();
       txtFN.setText(demographic.getFirstName());
       txtLN.setText(demographic.getLastName());
       txtDOB.setText(demographic.getDOB());
       txtAge.setText(demographic.getAge());
       txtHeight.setText(demographic.getHeight());
       txtWeight.setText(demographic.getWeight());
       txtSSN.setText(demographic.getSSN());
       txtStreet.setText(addres.getStreatAdrss());
       txtCity.setText(addres.getCity());
       txtState.setText(addres.getState());
       txtZipCode.setText(addres.getZipcode());
       txtSABank.setText(savings.getBname());
       txtSAAcc.setText(savings.getBAccNo());
       txtSARoute.setText(savings.getBRountingNo());
       txtCHBank.setText(checkings.getCBname());
       txtCHAcc.setText(checkings.getCBAccNo());
       txtCHRoute.setText(checkings.getCBRountingNo());
       txtDL.setText(driver.getLicNo());
       txtDOI.setText(driver.getIssuedDate());
       txtDOE.setText(driver.getExpireyDate());
       txtBloodGrp.setText(driver.getBloodType());
       txtMedical.setText(medical.getMedRecordNo());
       txtAlergy1.setText(medical.getAlergy1());
       txtAlergy2.setText(medical.getAlergy2());
       txtAlergy3.setText(medical.getAlergy3());
       if(driver.getPicture() == null) {
            String imagePath;
            imagePath = "";
            driver.setPicture(imagePath);
        }
        try {
            bufferedImage = ImageIO.read(new File(driver.getPicture()));
            lblImage.setIcon(new ImageIcon(new ImageIcon(bufferedImage).getImage().getScaledInstance(180, 180, Image.SCALE_DEFAULT)));
        } catch (IOException e) {

        }
    }
}
